# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XLFormTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XLFormTest
  pod 'XLForm', '~> 3.1.1'
  pod 'SVProgressHUD', '~> 2.2.5'
end
